### PR TITLE
Do not obsucre original function.

### PR DESCRIPTION
**Pull request by mfalesni**
- Uses `@wraps` to transfer properties from the wrapped function to the wrapper so we can see the function name that failed in wait_for()

### CODE REVIEW

**Comment by weissjeffm** [comment]
I am not sure I understand what purpose this serves, since the wrapper function calls the original.  Where are you seeing output that is missing this information?

**Comment by mfalesni** [comment]
Last 5.2.z jenkins build, `cfme/tests/services/test_ec2_service_catalogs.py/test_ec2_catalog_item[ec2west]`

It calls the function, but it does not transfer the function's parameters there so the `__name__` parameter does not represent the function.

So every traced function is basically renamed to `traced_fn` for all objects that access them.

**Comment by weissjeffm** [comment]
Ah I understand now.

**Comment by weissjeffm** [comment]
Pushed to pypi.  Thanks @mfalesni.

**Pull request merged**
